### PR TITLE
Add Dark and light mode. From system info

### PR DESCRIPTION
**Pull request by ARR4NN**
Add dark mode and light mode based on the system theme.
Tested on local host and works nicely.

### CODE REVIEW

**Comment by ARR4NN** [comment]
Also added some icons
image

**Comment by EleKtr1X** [comment]
could use a little more work, and tbh i'm not a huge fan of the red

**Comment by ARR4NN** [comment]
> 
> 
> could use a little more work, and tbh i'm not a huge fan of the red

What would be a better color?

**Comment by EleKtr1X** [comment]
> 
> 
> > could use a little more work, and tbh i'm not a huge fan of the red
> 
> What would be a better color?

white or a light grey (e.g. #CCC)

**Pull request closed without merging**
